name: Deploy to Server

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: nanshukur
          password: N@NT@ch96

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA1OSAZ9R9f7ax0bSCozcWxYOueEtSAARkFQgS+PdVvcSlYW4C9BUb
3oP8HBh6RtKCc5PgT65fBVXK0RymlMS0waru84rXuPH9LCI34VCxDY89DyC1IK+2xxQCLE
FEfJCU3wThlu59DkcpbJHkIbr1jaOchfCQMNPv7/YddX886Esaip+/yxbFXRYukruhxzbm
0JXkiIApbILiTQQRFelaw0I/bUAhXJzd0SXeI3AtAImnnTSNQRrnRBLV92q6kor9Z5EEzU
gMSxZfIOKTo207CPiAX8eL+sq/yjKHKQGwvP7iTHLpuK9ORcEFu534Y5TeH/y6CgXb+wjw
Lo9p/rSMoglNP+o1mND830v3iVGfHZKMbYyZeWg3zYHQYTISDbEVS6NMyoEMXf6tOmEemX
JAiFyGs9RfcpLfNxfTFkZ//BE9XcLu5JY2dV/ZLp3VdfCWOszy59m6rMQ3REvjrqNJZOJr
Gm01tu+2Nhthzrq0kyxLZsmNATT1sqypVMpIw63oNFbltepm2R/jV0E2lRP/fIJIF1mirO
jJMijveOfvf7Pw1gw6GoloqQMO1ur787yFKR8UyhpiAw64ALDZrfBBIA3e+dKj+xCjx60i
CF3dp2JPZNXekqmP7l4z2a62wdU+fdFwwxTBWQgHREq2gbdlP920MQmF+LVfYPnvVM1Q+r
kAAAdQEmk1zxJpNc8AAAAHc3NoLXJzYQAAAgEA1OSAZ9R9f7ax0bSCozcWxYOueEtSAARk
FQgS+PdVvcSlYW4C9BUb3oP8HBh6RtKCc5PgT65fBVXK0RymlMS0waru84rXuPH9LCI34V
CxDY89DyC1IK+2xxQCLEFEfJCU3wThlu59DkcpbJHkIbr1jaOchfCQMNPv7/YddX886Esa
ip+/yxbFXRYukruhxzbm0JXkiIApbILiTQQRFelaw0I/bUAhXJzd0SXeI3AtAImnnTSNQR
rnRBLV92q6kor9Z5EEzUgMSxZfIOKTo207CPiAX8eL+sq/yjKHKQGwvP7iTHLpuK9ORcEF
u534Y5TeH/y6CgXb+wjwLo9p/rSMoglNP+o1mND830v3iVGfHZKMbYyZeWg3zYHQYTISDb
EVS6NMyoEMXf6tOmEemXJAiFyGs9RfcpLfNxfTFkZ//BE9XcLu5JY2dV/ZLp3VdfCWOszy
59m6rMQ3REvjrqNJZOJrGm01tu+2Nhthzrq0kyxLZsmNATT1sqypVMpIw63oNFbltepm2R
/jV0E2lRP/fIJIF1mirOjJMijveOfvf7Pw1gw6GoloqQMO1ur787yFKR8UyhpiAw64ALDZ
rfBBIA3e+dKj+xCjx60iCF3dp2JPZNXekqmP7l4z2a62wdU+fdFwwxTBWQgHREq2gbdlP9
20MQmF+LVfYPnvVM1Q+rkAAAADAQABAAACAQCueS466cyIdGO652MA/E7vRIIiGCh11yNm
kR1raNieE6Et/gjxnLMgY66kH/NmQ3Oh4Rk+dDtvleYIBqEG30b8SWhXs/wjmD7SgqClSY
oxAKkb0sReq2LyOJWnSz4jkCJRvCBdn8phfzSVw+LhOeWwVNwccRDa03aahGuUNdjmz1ZL
MazvdhP9vAYjPx7Qs0/qtk17CP3p7kIkuCaAfKRjzdFJaftteSnZFF2/UVmwTSBPGBiDuN
a71WwBvzh0jPAsho8W5esdRpJj0w0ILKbrLS2YUWOI/8y6mzpmAvqjiYhQ+wRM1W8if5SB
NG+yvPhl4qtdN3wXejXNEr/dfH6bdf4Q7QOTgabJBYCKNNavPU9HmgNB97aD4zRMevWpfr
BAWIWKQ2pMcYoAOed0+kPrNbrDTb3TJSHxC6k9/iclj9B1sbYe69BMLZTY7zJYiX7eeuTe
1l+4AMUG5Lcy3V9mJDzZ8qJRSyfFyRlzqUmW4egFz4vHiu7WZYqVhWFU5wE66anpVDZrBI
720e5SYmPri5GMK1cYX4NlDH0NQ5+xTqlFjHGCzaQpqnMLKglwKVm4LOXb/ggXgdr1bOTD
xsdou9+DTMGU1afT4O8wx6io+Req9zaR5Sl98yRiU3+mToaeMVM45qOgJ7Ql01MJWEDbaO
d8KQzBI82LdxjXzucFeQAAAQEA4ZK2WC71ZPfm+7h7sKS+yhRBCXjYZ/FBO9odsZMpd2qc
IRvIA75468n4Jrh9qgqA/m0nOzwMblMtwI5IZim3oKM3DGmmWeq19pJyQgGr2cmsqjRDZy
d+pqOat2FDluxSG7N97BDVpauHRSw+S403Pd4GAY6nT+tctKpQg/a6NytG5oaB9GdWIwAy
sOwkheeVUCmrvlNEE5gP74bdDjeKTeXqRN+fHconhEljOtoh05cjnUKpt9JafGj/Hxwx4U
2StXCSDYcaimP5x9cU8yWRmZ896AOJd/Qw+7HeWIKjT09H+N3srABT6YRUFio5IeohzaaN
jRbkMoshuIPPQXh6BgAAAQEA+FJjVU7XMpZuXDoMwLHTQYK33sw0aSCNGyk1c8y5sJ5Gwz
ZXRU2TrvYnOhHt6bmo8KnuJs6xdmxOVjmBbXXQTKOXrRsZU3ez1g9eAIf5nH6zfAOAJn5X
wqcPw4I5pFLPKMOpAgtpko2/u5EXWnTQEqpV6TuhSvVSArrLn4KXEITHf3L2iPfX9zBJYk
ozhQFIcz8yMpXa0Lh0MM/TOSkeQt4pLQsxzu+t3PwbTeNyX9EprLZCfUHFXrJ15AfRMgog
akNmPIEjtBZdCG8XCXu6kbyOKgG9ZUJ/bKSi0KroZ9w/Pd2S4ktRDIFcqofFhCZwRbys5c
LA/YyGPcHEdR3tCwAAAQEA23mror/+dcBehJrCrCEBM3Iu922ZhJ9LVhgHm8CXzlpUjien
Il3aabCG6IRDRpg3FeMndjaeYQgCSWHJ0HIDAt42EJXRrTDS9HuReEWL1FGaDIqUSb6TQI
zhQaq3tmFTFYGWgNAME73pRHg9a8IyZ/H/629XF8ttQTEMvLwAZpC5jmobMuCSKlbRqHyB
DRb6pVc8ZC/HQxGC8/eGfROXQvELAiJvNbwpPu5WxZjhg7OtDYq/YWTPy48wG148vT8TOP
477qb+o8l0oUWMDOjAkLOckzQs+m1aXnpqo8+whZBSbHv3MT92XVOt6tuAjr+gp+a26u8W
C8ZQG5uuVeXpywAAABludXJsYW4uc2h1a3Vyb3ZAZ21haWwuY29t
-----END OPENSSH PRIVATE KEY-----
      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 109.199.105.149 >> ~/.ssh/known_hosts

      - name: Build and push Docker image
        run: |
          docker build -t nanshukur/testapi -f ./testapi/Dockerfile ./testapi
          docker push nanshukur/testapi

      - name: Deploy to server
        env:
          DOCKER_HOST: ssh://root@109.199.105.149
        run: |
          docker pull nanshukur/testapi
          docker stop testapi-container || true
          docker rm testapi-container || true
          docker run -d -p 5000:80 --name testapi-container \
          nanshukur/testapi
