name: Deploy to Server

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 109.199.105.149 >> ~/.ssh/known_hosts

      - name: Build and push Docker image
        run: |
          docker build -t nanshukur/testapi -f ./testapi/Dockerfile ./testapi
          docker push nanshukur/testapi

      - name: Deploy to server
        env:
          DOCKER_HOST: ssh://root@109.199.105.149
        run: |
          docker pull nanshukur/testapi
          docker stop testapi-container || true
          docker rm testapi-container || true
          docker run -d -p 5000:80 --name testapi-container nanshukur/testapi
